;Projeto Final
LIST   P=PIC16F628A
RADIX DEC	
#INCLUDE <P16F628A.INC>
	__CONFIG _INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_ON & _BODEN_OFF & _LVP_OFF & _CP_OFF & _MCLRE_OFF & _DATA_CP_OFF 
	;ou __CONFIG H'3F10'
	#DEFINE BANK0 BCF STATUS,RP0;SETA BANK 0 DE MEMÓRIA
	#DEFINE BANK1 BSF STATUS,RP0;SETA BANK 1 DE MAMÓRIA
	CBLOCK	0x20	;ENDEREÇO INICIAL DA MEMORIA DE
					;USUÁRIO
	CONTADOR1
	CONTADOR2
	CONTADOR3
	CONTADOR4
	CONTADOR5
	ENDC ;FIM DO BLOCO DE MEMORIA
	#DEFINE BTN  PORTA,2  ;PORTA DO BOTÃO ;0=>PRESSIONADO
										  ;1=>LIBERADO
	#DEFINE VERMELHO1 PORTB,0 
	#DEFINE VERMELHO2 PORTB,3
	#DEFINE AMARELO1 PORTB,1
	#DEFINE AMARELO2 PORTB,4
	#DEFINE VERDE1 PORTB,2
	#DEFINE VERDE2 PORTB,5			
	
	ORG	0x00		;ENDEREÇO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
		
INICIO
	CLRF PORTA;LIMPA O PORTA
	CLRF PORTB;LIMPA O PORTB
	BANK1;ALTERA PARA O BANCO 1
	MOVLW B'00000100'
	MOVWF TRISA;DEFINE RA1 COMO ENTRADA E DEMAIS COMO SAÍDAS
	MOVLW B'00000000'
	MOVWF TRISB;DEFINE TODO O PORTB COMO SAÍDA
	MOVLW B'00000000'
	MOVWF INTCON;TODAS AS INTERRUPÇÕES DESLIGADAS
	BANK0;RETORNA PARA O BANCO 0
	MOVLW B'00000111'
	MOVWF CMCON;
REPETE
	BSF  VERDE2		  ;ACENDE UM LED VERDE
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERDE2		  ;DESLIGA O LED VERDE ACESO
	
	BSF  AMARELO1     ;ACENDE UM LED AMARELO
	CALL ATRASO       ;Vai para ATRASO
	BCF  AMARELO1     ;DESLIGA O LED AMARELO ACESO

	BSF  VERDE1		  ;ACENDE UM LED VERDE
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERDE1		  ;DESLIGA O LED VERDE ACESO	

	BSF  VERMELHO2    ;ACENDE UM LED VERMELHO
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERMELHO2    ;DESLIGA O LED VERMELHO ACESO

	BSF  VERDE2       ;ACENDE UM LED VERDE
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERDE2       ;DESLIGA O LED VERDE ACESO 

	BSF  VERMELHO1    ;ACENDE UM LED VERMELHO
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERMELHO1    ;DESLIGA O LED VERMELHO ACESO

	BSF  AMARELO1     ;ACENDE UM LED AMARELO
	CALL ATRASO       ;Vai para ATRASO
	BCF  AMARELO1     ;DESLIGA O LED AMARELO ACESO

	BSF  VERMELHO2	  ;ACENDE UM LED VERMELHO
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERMELHO2    ;DESLIGA O LED VERMELHO ACESO

	BSF  AMARELO2     ;ACENDE UM LED AMARELO
	CALL ATRASO       ;Vai para ATRASO
	BCF  AMARELO2     ;DESLIGA O LED AMARELO ACESO

 	BSF  VERDE2       ;ACENDE UM LED VERDE
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERDE2       ;DESLIGA O LED VERDE ACESO

	BSF  AMARELO1	  ;ACENDE UM LED AMARELO
	CALL ATRASO       ;Vai para ATRASO
	BCF  AMARELO1     ;DESLIGA O LED AMARELO ACESO

	BSF  VERMELHO1    ;ACENDE UM LED VERMELHO
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERMELHO1    ;DESLIGA O LED VERMELHO ACESO

	BSF  AMARELO1	  ;ACENDE UM LED AMARELO
	CALL ATRASO       ;Vai para ATRASO
	BCF  AMARELO1     ;DESLIGA O LED AMARELO ACESO

	BSF  VERDE1       ;ACENDE UM LED VERDE
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERDE1       ;DESLIGA O LED VERDE ACESO

	BSF  VERMELHO2    ;ACENDE UM LED VERMELHO
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERMELHO2    ;DESLIGA O LED VERMELHO ACESO

	BSF  AMARELO1     ;ACENDE UM LED AMARELO
	CALL ATRASO       ;Vai para ATRASO
	BCF  AMARELO1     ;DESLIGA O LED AMARELO ACESO

 	BSF  VERDE1       ;ACENDE UM LED VERDE
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERDE1       ;DESLIGA O LED VERDE ACESO

	BSF  VERMELHO2	  ;ACENDE UM LED VERMELHO
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERMELHO2    ;DESLIGA O LED VERMELHO ACESO

	BSF  VERDE2       ;ACENDE UM LED VERDE
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERDE2       ;DESLIGA O LED VERDE ACESO

	BSF  AMARELO2     ;ACENDE UM LED AMARELO
	CALL ATRASO       ;Vai para ATRASO
	BCF  AMARELO2     ;DESLIGA O LED AMARELO ACESO
	
	BSF  VERMELHO2	  ;ACENDE UM LED VERMELHO
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERMELHO2    ;DESLIGA O LED VERMELHO ACESO
	
	
	BSF  VERDE1       ;ACENDE UM LED VERDE
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERDE1       ;DESLIGA O LED VERDE ACESO
	
	BSF  VERMELHO1    ;ACENDE UM LED VERMELHO
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERMELHO1    ;DESLIGA O LED VERMELHO ACESO

	BSF  AMARELO1	  ;ACENDE UM LED AMARELO
	CALL ATRASO       ;Vai para ATRASO
	BCF  AMARELO1     ;DESLIGA O LED AMARELO ACESO

	BSF  VERDE1       ;ACENDE UM LED VERDE
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERDE1       ;DESLIGA O LED VERDE ACESO

	BSF  VERMELHO2    ;ACENDE UM LED VERMELHO
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERMELHO2    ;DESLIGA O LED VERMELHO ACESO

	BSF  AMARELO1     ;ACENDE UM LED AMARELO
	CALL ATRASO       ;Vai para ATRASO
	BCF  AMARELO1     ;DESLIGA O LED AMARELO ACESO

	BSF  VERDE2		  ;ACENDE UM LED VERDE
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERDE2		  ;DESLIGA O LED VERDE ACESO
	
	BSF  AMARELO1     ;ACENDE UM LED AMARELO
	CALL ATRASO       ;Vai para ATRASO
	BCF  AMARELO1     ;DESLIGA O LED AMARELO ACESO

	BSF  VERDE1		  ;ACENDE UM LED VERDE
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERDE1		  ;DESLIGA O LED VERDE ACESO	

	BSF  VERMELHO2    ;ACENDE UM LED VERMELHO
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERMELHO2    ;DESLIGA O LED VERMELHO ACESO

	BSF  VERDE2       ;ACENDE UM LED VERDE
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERDE2       ;DESLIGA O LED VERDE ACESO 

	BSF  VERMELHO1    ;ACENDE UM LED VERMELHO
	CALL ATRASO       ;Vai para ATRASO
	BCF  VERMELHO1    ;DESLIGA O LED VERMELHO ACESO

	GOTO REPETE       ;Volta para inicio
 			
ATRASO  ;GERA O ATRASO ENTRE OS LEDS
	MOVLW 32     ;32 EASY,16 HARD,8 VERY HARD,1 IMPOSSIBLE
	MOVWF CONTADOR1
ATRASO1
	CALL BTN_ATR     ;CHAMA O ATRASO DE VERIFICAÇÃO DO BOTÃO
	BTFSS  BTN       ;SE O BOTAO ESTA PRESSINADO EXECUTA A PROXIMA LINHA CASO COTRÁRIO PULA A PROXIMA LINHA
	CALL   BTN_PRESS ;CHAMA A FUNÇÃO QUE ANALISA SE O BOTÃO FOI PRESSIONADO NO MOMENTO CERTO
	DECFSZ CONTADOR1 ;FAZ O LOOP DE REPETIÇÃO DO ATRASO
	GOTO   ATRASO1   ;FAZ O LOOP DE REPETIÇÃO DO ATRASO
	RETURN           ;RETORNA PARA INICIO

BTN_ATR              ;GERA O ATRASO DE VERIFICAÇÃO DO BOTÃO
	MOVLW 255			
	MOVWF CONTADOR4
	MOVLW 40
	MOVWF CONTADOR5
BTN_ATR_1
	DECFSZ CONTADOR4
	GOTO   BTN_ATR_1
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	DECFSZ CONTADOR5
	GOTO   BTN_ATR_1
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	RETURN ;RETORNA PARA ATRASO 
	
BTN_PRESS   ;VERIFICA SE O BOTÃO FOI PRESSIONADO NO MOMENTO CERTO
	BTFSC   VERMELHO1 ;SE O LED VERMELHO1 ESTÁ APAGADO PULA A PROXIMA LINHA
	GOTO    FIMCLEAR  ;VAI PARA A RESPOSTA DE 'acertou' DO JOGO
	BTFSC   VERMELHO2 ;SE O LED VERMELHO2 ESTÁ APAGADO PULA A PROXIMA LINHA
	GOTO    FIMCLEAR  ;VAI PARA A RESPOSTA DE 'acertou' DO JOGO
	GOTO    ERRROW    ;VAI PARA A RESPOSTA DE 'errou' DO JOGO
VOLTA
	RETURN  ;VOLTA PARA ATRASO
FIMCLEAR ;GERA A RESPOSTA DE ACERTOU DO JOGO
	BSF  VERMELHO1
	BSF  VERMELHO2
	BSF  AMARELO1
	BSF  AMARELO2
	BSF  VERDE1
	BSF  VERDE2
	;ACENDE TODOS OS LEDS
	CALL FIMCLEAR_ATRASO ;ESPERA UM TEMPO DE VISUALIZAÇÃO DA RESPOSTA
	CLRF PORTA;LIMPA O PORTA
	CLRF PORTB;LIMPA O PORTB
	GOTO VOLTA;VOLTA PARA BTN_PRESS
FIMCLEAR_ATRASO ;GERA O TEMPO DE VISUALIZAÇÃO DA RESPOSTA
	MOVLW 255
	MOVWF CONTADOR2
	MOVLW 255
	MOVWF CONTADOR3
FIMCLEAR_ATRASO_1
	DECFSZ CONTADOR2
	GOTO FIMCLEAR_ATRASO_1
	DECFSZ CONTADOR3
	GOTO FIMCLEAR_ATRASO_1
	RETURN
ERRROW  ;GERA A RESPOSTA DE ERROU DO JOGO
	BSF  VERMELHO1
	BSF  VERMELHO2
	;ACENDE OS LEDS VERMELHOS
	CALL ERRROW_ATRASO;ESPERA UM TEMPO DE VISUALIZAÇÃO DA RESPOSTA
	CLRF PORTA;LIMPA O PORTA
	CLRF PORTB;LIMPA O PORTB
	GOTO VOLTA
ERRROW_ATRASO  ;GERA O TEMPO DE VISUALIZAÇÃO DA RESPOSTA
	MOVLW 255
	MOVWF CONTADOR2
	MOVLW 255
	MOVWF CONTADOR3
ERRROW_ATRASO_1
	DECFSZ CONTADOR2
	GOTO ERRROW_ATRASO_1
	DECFSZ CONTADOR3
	GOTO ERRROW_ATRASO_1
	RETURN
END
